import logging
from typing import List, Tuple, Optional
from sqlalchemy.orm import Session

from app.core.config import settings
from app.models.interview import Interview
from app.models.interview_question import InterviewQuestion
from app.ai.providers.factory import get_ai_provider
from app.ai.evaluation.answer.exceptions import AIProviderError, AIProviderTimeoutError, AIValidationError

logger = logging.getLogger(__name__)


def generate_and_store_interview_questions(
    db: Session,
    user_id: str,
    interview_id: str,
    number_of_questions: int = 5,
    provider_name: Optional[str] = None,
    mock_mode: Optional[str] = None
) -> Tuple[List[InterviewQuestion], str]:
    """
    Generate interview questions tailored to the specified interview configuration via AI Provider,
    and persist generated questions into the database attached to the owned Interview record.
    """
    # 1. Ownership & Existence Check
    interview = db.query(Interview).filter(
        Interview.id == interview_id,
        Interview.user_id == user_id
    ).first()

    if not interview:
        logger.warning(f"Interview '{interview_id}' not found or unauthorized for user '{user_id}'")
        raise KeyError(f"Interview '{interview_id}' not found or unauthorized.")

    # 2. Extract Interview Parameters for AI Prompt Engine
    interview_meta = {
        "title": interview.title,
        "job_role": interview.job_role or "Software Engineer",
        "interview_type": interview.interview_type or "Technical",
        "mode": interview.mode or "General",
        "domain": interview.domain or interview.interview_type or "General",
        "difficulty": interview.difficulty or "Medium",
        "experience_level": interview.experience_level or "2+",
        "counter_questions": getattr(interview, "counter_questions", True),
        "question_count": number_of_questions
    }

    selected_provider = provider_name or settings.AI_PROVIDER or "groq"
    logger.info(f"Generating {number_of_questions} questions for interview '{interview_id}' using provider '{selected_provider}'")

    # 3. Instantiate AI Provider & Generate Questions
    ai_provider = get_ai_provider(provider_name=selected_provider, mock_mode=mock_mode)
    raw_questions = ai_provider.generate_questions(
        interview_meta=interview_meta,
        number_of_questions=number_of_questions
    )

    if not raw_questions:
        logger.error(f"No valid questions generated by AI provider '{selected_provider}'")
        raise AIValidationError("AI provider failed to generate valid interview questions.")

    # 4. Clear old un-answered initial questions for this interview setup if replacing
    db.query(InterviewQuestion).filter(
        InterviewQuestion.interview_id == interview_id
    ).delete()

    # 5. Persist Generated Questions into Database
    created_records = []
    for idx, item in enumerate(raw_questions):
        question_obj = InterviewQuestion(
            interview_id=interview_id,
            question_text=item["question_text"],
            question_order=idx + 1,
            question_type=item.get("question_type", (interview.interview_type or "technical").lower()),
            generation_provider=selected_provider
        )
        db.add(question_obj)
        created_records.append(question_obj)

    db.commit()
    for record in created_records:
        db.refresh(record)

    logger.info(f"Successfully generated and persisted {len(created_records)} questions for interview '{interview_id}'")
    return created_records, selected_provider
