from app.core.config import settings

STT_MODEL_SIZE = settings.STT_MODEL_SIZE
STT_DEVICE = settings.STT_DEVICE
STT_COMPUTE_TYPE = settings.STT_COMPUTE_TYPE
STT_LANGUAGE = settings.STT_LANGUAGE
MAX_AUDIO_SIZE_MB = settings.MAX_AUDIO_SIZE_MB
MAX_AUDIO_DURATION_SECONDS = settings.MAX_AUDIO_DURATION_SECONDS
